name: x_clone_app_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: 1.2.2
  serverpod_auth_server: 1.2.2
  serverpod_chat_server: 1.2.2

dev_dependencies:
  lints: ^3.0.0
